### ISSUE TITLE
Implement Discord Client and Command Handler

### ISSUE THREAD

**Issue by petrspelos** [discord-bot-tutorial/Miunie#1]
Inside `Miunie.Discord` project, we need to reference the `DSharpPlus` NuGet package and implement a basic Discord Client.

This requires the creation of `DSharpClient` and `CommandHandler` according to the following structure:

![image](https://user-images.githubusercontent.com/21304428/50551780-ed6ceb00-0c86-11e9-8fbd-97035ef8ab3b.png)

------------------------
:information_source: You are free to change up the structure by for example creating more classes or naming them differently. In that case, make sure to document your changes and the reasoning behind them in your Pull Request.

**Comment by DraxCodes** [comment]
Peter gave me this Idea... Bad Peter.
