### ISSUE TITLE
Flesh out README

### ISSUE THREAD

**Issue by petrspelos** [discord-bot-tutorial/Miunie#11]
Our new `README.md` should be as fleshed out as the [original README](https://github.com/discord-bot-tutorial/Community-Discord-BOT/blob/master/README.md).

README inspiration:
* [PurpleBoot template](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2)
* [Jehna's best practices](https://github.com/jehna/readme-best-practices)

**Comment by DraxCodes** [comment]
I'll give this a shot :)
