### ISSUE TITLE
Adding a reason to the reputation commands.

### ISSUE THREAD

**Issue by svr333** [discord-bot-tutorial/Miunie#111]
What I mean with this is that the user that gives/removes rep off of someone, can provide a reason for doing so.

For example:
`@bot +rep @petrspelos Cool new video, deserves a reputation!`
`@bot -rep @DraxCodes Didn't join voice chat last night, I'll have to take this from you. :(`

That's all there is to it.

**Comment by Charly6596** [comment]
is someone working on this one? i'd like to do it (:
Also one question, would the reason be an optional or a mandatory parameter?
I'd make it optional, to be more flexible :thinking:

**Comment by svr333** [comment]
I don't think anyone is on this atm, and I would make it optional too.
Whenever someone gets to #112 , we can put `no reason provided` whenever there was no reason provided. And unless this is an issue for like beginners, I feel like you can take this one :)

**Comment by Charly6596** [comment]
Uh, I don't mind doing #112 instead, but it's been a while since I was active with Miunie, I feel beginner to be honest :disappointed:

**Comment by svr333** [comment]
I mean, you can do whatever you want in my opinion 🤷‍♂️
But I feel like @petrspelos has an opinion of bigger power.

**Comment by svr333** [comment]
He confirmed that you can do it, @Charly6596
