### ISSUE TITLE
UWP InvalidCastException

### ISSUE THREAD

**Issue by petrspelos** [discord-bot-tutorial/Miunie#126]
![obrazek](https://user-images.githubusercontent.com/21304428/56139894-12693d80-5f9a-11e9-85e7-73527daf27fe.png)

@svr333 encountered this exception every time he tried to open the settings pane. It has never happened for me. Repro is needed for this one. Will try this one with Drax during LiveShare.

**Comment by DraxCodes** [comment]
Most likley caused by outdated version of Windows 10.
Requires 1809
