### ISSUE TITLE
Add '#' in front of channel names

### ISSUE THREAD

**Issue by petrspelos** [discord-bot-tutorial/Miunie#135]
> 🌷 This issue is **perfect** for beginners and first-time contributors. 🙂 

## About

Currently the text channel names are displayed without the `#` symbol in front of them.

The task is to simply add the `#`.

![problem demonstration](https://i.imgur.com/a9stZLE.png)

## Where to look

See if you can figure out how the channel name gets added in `Miunie.Discord/Impersonation.cs`.

You could probably change it there.

⚠️ This file doesn't exist until the Impersonation PR gets merged.

**Comment by Kallashnikovv** [comment]
I'd like to take this one.
