### ISSUE TITLE
Style message display & add an Avatar

### ISSUE THREAD

**Issue by petrspelos** [discord-bot-tutorial/Miunie#136]
> 💾 This issue is **perfect** for beginners and first time contributors. :tada:

## About

The last 10 messages view isn't formatted very well. It also only uses 2 out of 3 parameters it has available. (It doesn't use `AuthorAvatarUrl`)

![problem demonstration](https://i.imgur.com/lp5XZrK.png)

The task is to display an avatar of each message's author next to it.

💡 You can use the [`<PersonPicture>`](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/person-picture) component.

🖼 ✏️  If you're feeling creative, feel free to also make the messages look stylish. 😊 

## Where to look

You'll work in the `Miunie.WindowsApp/Views/ImpersonationChatPage.xaml` file. 😊 

-------------------

> ℹ️ If you would like to take this issue, please comment bellow so others know you're on it. 😉

**Comment by Kallashnikovv** [comment]
I'm aware that it's mine now 😏
