### ISSUE TITLE
Remove LangResourcesCollection

### ISSUE THREAD

**Issue by DraxCodes** [discord-bot-tutorial/Miunie#143]
❗️ This issue is specifically for our newcomers. It is ideal for if you wish to use this issue as a learning tool for your first PR into Miunie 👍 

In Miunie.ConsoleApp/Resources there is a folder named: `LanguageResourceCollection`
This folder simply needs removing as we're not using the `PhrasesEn.json` anymore. 

If you need help on your first PR. Check out: [Contributing to Miunie](https://github.com/discord-bot-tutorial/Miunie/blob/master/docs/CONTRIBUTING.md)

**Comment by TimmmyGotPasion** [comment]
i licked it so its mine now REEEEEEEEEEE
