### ISSUE TITLE
Empty or invalid token UI handling

### ISSUE THREAD

**Issue by CakeAndBanana** [discord-bot-tutorial/Miunie#148]
## About

When no bot token is set, Miunie crashes on start.
While this should be handled in the Core, the GUI shouldn't let the user get that far.

So the task is to make sure the user doesn't start the bot when there is no token set **and** they understand the reason.

## The How

💡 One option is to disable the button and add a warning text underneath it.

**Comment by petrspelos** [comment]
@CakeAndBanana what is the status of this issue, did you perhaps get stuck on something. 😊

**Comment by CakeAndBanana** [comment]
@petrspelos Update on this issue.

After @Ggglitch had fixed issue #149 I was able to get it working with a PasswordBox inside the Settings page for inputting the bot key. The key will be saved inside local data so you don't have to re-enter the key after a restart or crash. An issue is that you have to load the Settings page to load the key, I will look for a solution for that today ;). I haven't created the warning text underneath the button but it should be an easy job because there are error messages now when loading the bot. 

Connecting to bot with correct key and incorrec key:
![2019-05-04_02-17-02](https://user-images.githubusercontent.com/48980200/57180697-3697aa80-6ec6-11e9-9612-733633002332.gif)
