### ISSUE TITLE
Null, Empty, or invalid token exception handling

### ISSUE THREAD

**Issue by petrspelos** [discord-bot-tutorial/Miunie#149]
> 🥇 This issue is great for new contributors and Miunie beginners.

## About

When Miunie tries to connect and the bot token is either Null, empty, or invalid, there is an exception thrown.

This exception should be caught, logged, and the operation safely aborted.

## The How

💡 The most likely part of the code base is the following
https://github.com/discord-bot-tutorial/Miunie/blob/343e51c6f0ef425d92b769396c456813c2bb3389/src/Miunie.Discord/MiunieDiscord.cs#L52-L65

-----------

> ℹ️ If you'd like to work on this issue, please comment bellow so that others know this is being worked on. 😊 Thanks! ⭐️

**Comment by Ggglitch** [comment]
I would like to try, seems easy enough :)

**Comment by DraxCodes** [comment]
You are more than welcome to :+1:

**Comment by TimmmyGotPasion** [comment]
is this already done or still open? ^^

**Comment by Ggglitch** [comment]
I'm gonna fix a couple of things so that console app doesn't crash.
