### ISSUE TITLE
Implement a Blazor Front End.

### ISSUE THREAD

**Issue by DraxCodes** [discord-bot-tutorial/Miunie#164]
This is going to be an ongoing issue as I slowly find time to implement a Blazor front end.

ℹ️ Due to blazor requireing Core 3.0 I will most likley implement this if or when we decide to make the leap to 3.0. Creating the issue now so it is ready to be worked on.

**Comment by DraxCodes** [comment]
⚠️ It also seems blazor in unstable as of writing this comment. Intellisence has a hard time understanding the function bindings and it was a giant pain to get even the boilerplate code to even debug without shouting that MVC wasn't found. 

I will keep this issue updated as more updates come through for Blazor.

**Comment by petrspelos** [comment]
We'll close this and reopen when Blazor gets a foothold.
