### ISSUE TITLE
Migrate docs onto the Wiki

### ISSUE THREAD

**Issue by DraxCodes** [discord-bot-tutorial/Miunie#169]
Move docs onto wiki section.

ℹ️ Add a summary as each thing gets migrated.

**Comment by petrspelos** [comment]
I'm on it, chief. 
![bitmoji](https://render.bitstrips.com/v2/cpanel/2d04b78c-414a-4ce3-8bcc-71abe3d01964-5c8412f7-ff21-4a42-9606-71a02e19d8db-v1.png?transparent=1&palette=1&width=246)
