### ISSUE TITLE
Refactor Naming Of Core, Tests & Main README.md.

### ISSUE THREAD

**Issue by DraxCodes** [discord-bot-tutorial/Miunie#170]
### 1️⃣ The naming of these two methods should be changed:

https://github.com/discord-bot-tutorial/Miunie/blob/1f62659883c8a042c238e76607d8ef13ae1932cc/src/Miunie.Core/Providers/UserReputationProvider.cs#L34-L38

```diff
- public bool TryAddReputation(MiunieUser invoker, MiunieUser target)
+ public bool CanAddReputation(MiunieUser invoker, MiunieUser target)
- public bool TryRemoveReputation(MiunieUser invoker, MiunieUser target)
+ public bool CanRemoveReputation(MiunieUser invoker, MiunieUser target)
```

-----

### 2️⃣ Rename Mocks folder in Unit Tests to Data.

![MocksImage](https://i.gyazo.com/34d3316e8680871ae17bec5d495807fa.png)

-----

### 3️⃣ Move the Service Tests (Shown below) to a Service Directory.

* [ProfileServiceTests.cs](https://github.com/discord-bot-tutorial/Miunie/blob/master/src/Miunie.Core.XUnit.Tests/ProfileServiceTests.cs)
* [ProfileServiceReputationTests.cs](https://github.com/discord-bot-tutorial/Miunie/blob/master/src/Miunie.Core.XUnit.Tests/ProfileServiceReputationTests.cs)

----

### 4️⃣ The license badge should be changed to reflect new GPL 3.0 license.

![BadgeImage](https://i.gyazo.com/adade8c8a574bfd9fee51c6e85245c91.png)

**Comment by Ggglitch** [comment]
I'm up for it

**Comment by DraxCodes** [comment]
All yours :)
