### ISSUE TITLE
Change service collection strategy

### ISSUE THREAD

**Issue by petrspelos** [discord-bot-tutorial/Miunie#27]
The [service collection of DSharpPlusDiscord](https://github.com/discord-bot-tutorial/Miunie/blob/master/src/Miunie.Discord/DSharpPlusDiscord.cs#L39&L44) needs to be refactored.

## What is going on?
Our current strategy is showing symptoms of unmanageable design.
When required services (ie. `ProfileService`) have dependencies, they need to be injected into `DSharpPlusDiscord` class in order to have their dependencies resolved.

This slowly creates a giant DSharpPlusDiscord constructor filled with services that are only used for [service collection registration](https://github.com/discord-bot-tutorial/Miunie/blob/master/src/Miunie.Discord/DSharpPlusDiscord.cs#L39&L44).

## Circular dependencies

Furthermore, circular dependencies can happen. For example `ProfileService` requires `IDiscordMessages`, which is implemented in `DSharpPlusDiscord`. The problem is that `DSharpPlusDiscord` requires `ProfileService` and thus creates a runtime exception.

Current temporary solution to this is instantiating a new `ProfileService` in `DSharpPlusDiscord`, however, this solution is temporary.

## Suggested solution
As @DraxCodes found out, the v4 of DS+ accepts a service collection, let's update to that version and pass in our service collection.

**Comment by DraxCodes** [comment]
Note; In DSharpPlus V4 they're using an IServiceProvider rather than they're own implementation.
According to the Dev, Version 4 is super stable with the only caveat being there may be slight changes to the Wrapper as it's still in development. 

![Image](https://i.gyazo.com/43518460111bed0c4826382e2a3ae53c.png)

**Comment by Charly6596** [comment]
@DraxCodes That's great news! +1 to update to v4, we could revert if anything goes wrong, and the benefit is higher than the risk, since our architecture is totally decoupled from the discord wrapper!

**Comment by Charly6596** [comment]
@DraxCodes That's great news! +1 to update to v4, we could revert if anything goes wrong, and the benefit is higher than the risk, since our architecture is totally decoupled from the discord wrapper!

**Comment by petrspelos** [comment]
@Charly6596 @DraxCodes Let's do it. :1st_place_medal:
