### ISSUE TITLE
Language resources

### ISSUE THREAD

**Issue by petrspelos** [discord-bot-tutorial/Miunie#35]
Currently in `Miunie.Core/Services/ProfileService.cs` we have a hardcoded response.

This response should come from another service injected into `ProfileService`'s constructor.

The new service would be something like a `LanguageService` or `LanguageResources` (probably resources, since we shouldn't spam the Service word).

It would interact with `IDataStorage` to get the needed resources from a persistent storage.

You would give it a phrase key and it would return the phrase.
ie.
```cs
var format = langRes.GetPhrase("MIUNIE_PROFILE_FORMAT");
```
:1st_place_medal: Bonus points if we could use a formatted response as well. For example, if `MIUNIE_PROFILE_FORMAT` returns `"You have {0} miunies."` and ideal call would be something like
```cs
var message = langRes.GetFormatted("MIUNIE_PROFILE_FORMAT", miunieAmount);
```
to get the already formatted message.

:page_facing_up: Note that we would need the `params object obj` for the possible number of parameters in format.

**Comment by Charly6596** [comment]
I'll do this.
