### ISSUE TITLE
Implement Type conversion between DSharp+ and Miunie objects

### ISSUE THREAD

**Issue by petrspelos** [discord-bot-tutorial/Miunie#36]
Currently, we use `EntityConvertor.cs` to handle the conversion. However, as @Charly6596 suggested, there is a way of having these objects be implicitly converted when passed into a DSharp+ command.

The goal is to implement this conversion in the DSharp+ way and get rid of the current `EntityConvertor.cs`.

**Comment by Charly6596** [comment]
I wrote a guide about doing that, it's in referenced in the [common-issues](https://github.com/discord-bot-tutorial/common-issues) repository.
- [Custom command parameter types converting DSharpPlus entities](https://github.com/Charly6596/DSharpConverterExample)

Basically, is about using the DSharpPlus converters to convert the user input to a DSharpPlus entity, and after that, conver the DSharpPlus entity to our entity.
