### ISSUE TITLE
Implement the "ls" command

### ISSUE THREAD

**Issue by petrspelos** [discord-bot-tutorial/Miunie#56]
We already have the `ls` command more or less working. It is being unit tested and the code is there.
The only thing that is missing is a **discord command** to invoke the `ls` implementation.

Currently, `ls` should output the default position of the user. At the moment this location will always include the `Data` directory, and a directory with the same name as the server where the user is invoking the command.

Calling `@Miunie ls` in the "Discord-Bot-Tutorial" server should work with the following structure:
```
📁 ROOT
    ├ 📁 Data
    └ 📁 Discord-Bot-Tutorial
```

See [ListDirectoryService](https://github.com/discord-bot-tutorial/Miunie/blob/master/src/Miunie.Core/Services/ListDirectoryService.cs) for the current implementation.

:bulb: It might be very cool to actually display the structure using the `📁` emoji and other visuals.

**Comment by OnesQuared** [comment]
Hey, was browsing and found this to be interesting, always wanted to try something with discord bots. Could I be able to take a crack at this? although I'm unfamiliar with discord functionality

**Comment by petrspelos** [comment]
Absolutely, thank you and go ahead. :heart:

**Comment by OnesQuared** [comment]
@petrspelos just a quick clarification, the idea of this command is that in the discord with the bot, prompting the ls command would show the directory setup of the user. Where is the Discord-Bot-Tutorial server? and the directory that is shown is the directory of the server?

**Comment by petrspelos** [comment]
@OnesQuared I think it might be best demonstrated with an example. We don't have a `cd` (Change Directory) command implemented, yet, but in this example, I assume it exists.

Assume the following directory structure
```
📁 ROOT
    ├ 📁 Data
    └ 📁 Discord-Bot-Tutorial
```

```
User: @bot ls
----------------------
Bot:
📁 Data
📁 Discord-Bot-Tutorial
----------------------
User: @bot cd Discord-Bot-Tutorial
----------------------
Bot: OK
----------------------
User: @bot ls
----------------------
Bot:
📁 #general
📁 #off-topic
📁 #rules
```
I hope this demonstrates the way it works.
Think of it as navigation. `ls` shows what is inside the directory you are at.
You can type the commands wherever the bot can "hear" you, while being "logically" somewhere else.

## Usecase for the command
As an administrator, you might want to see what channels are in a Server "TestServer".
The way you'd do it is you would first `cd` (change directory) into that server with
```
@bot cd TestServer
```
and then `ls` list out the contents
```
@bot ls
```
this would output the list of channels inside the TestServer server. :slightly_smiling_face: 
Feel free to ask if something is still unclear. :blush:

**Comment by OnesQuared** [comment]
@petrspelos 
Sorry about the delay on this issue, but had some few things to take care of in life.

Any who, I think I got the gist of it, but looking to see where the ls command is written down.

I assume all I need to do is know the ls command and just call it in the user command entered

**Comment by petrspelos** [comment]
@OnesQuared 
Yes, the only thing needed is to implement a command that will use the `Miunie/src/Miunie.Core/Services/ListDirectoryService.cs` service. _(should really be a provider, I will create an issue for that later)_

However, keep in mind you should respect the structure of
`Miunie.Discord` should contain the actual command, however, it should only delegate to a service inside
`Miunie.Core` (you should create that new service).

You can take a look at the Profile or Reputation command as an example.
