### ISSUE TITLE
Implement the "cd" service

### ISSUE THREAD

**Issue by petrspelos** [discord-bot-tutorial/Miunie#57]
This service should handle all the logic for the `cd` command. `cd` stands for Change Directory.
Miunie represents the server space as a tree similar to your operating system.
Here is the structure we decided to use:
```
📁 ROOT
    ├ 📁 Data
    │   └ 📁 UserAccounts
    │       └ 📄 u123456789.json
    └ 📁 SomeServer
          ├ 📁 Channels
          │   ├ 🏠 general
          │   └ 🏠 off-topic
          └ 📁 Users
                 └ 👤 123456789
```
:information_source: This structure will be extended based on implementation details and/or new features.

The `cd` service should only allow a user to navigate into directories (shown as `📁` ).

:information_source: Implementing this service will create a need for the `ListDirectoryService` to be reworked in order to display other directory contents.

_(This doesn't have to be done by the implementer of the `cd` service, just please create an issue for it)_

The `cd` service manipulates the [MiunieUser's cursor](https://github.com/discord-bot-tutorial/Miunie/blob/master/src/Miunie.Core/Entities/MiunieUser.cs#L10).

This cursor is a `List` of `ulong`s representing the current position in our tree structure.

The `ROOT`'s ID should be `0`.
The `Data`'s ID should be `1`.
etc.

These IDs should be constant and should never change.
You are free to pick different constants based on the implementation.
When referencing Channels, Users, or Servers, the ID should be the Discord ID.

:information_source: If the user seems to be in an invalid position, they should be redirected back to root (by emptying the `NavCursor` list).

-----
Ideally, this service would have Unit tests, if you are able to implement this feature, but can't for some reason add unit tests, feel free to PR your changes. Others will help you with the unit tests, especially if this is your first time contributing. :slightly_smiling_face: :+1:

**Comment by ael-mas** [comment]
Hey, I'd like to work on this issue if it's still up for grabs

**Comment by petrspelos** [comment]
@ael-mas sure thing! Looking forward to it. :slightly_smiling_face: :tada:
