### ISSUE TITLE
Possibly Implement User Info Command

### ISSUE THREAD

**Issue by DraxCodes** [discord-bot-tutorial/Miunie#65]
This command would ideally output Discord based stats such as how long the user has been on the server, the last time they where active, their roles, etc.

Let me know if this is something you guys would like implementing?

**Comment by petrspelos** [comment]
Sounds really cool, maybe we could add it to the profile command? :+1:

**Comment by svr333** [comment]
Yeah, sounds amazing. I can possibly do it at the end of this week, if no one else has done it by then.

**Comment by petrspelos** [comment]
@svr333 Sure thing!

**Comment by svr333** [comment]
One thing though, I would prefer using an embed for that - since it looks cleaner and more organized in my opinion. But yesterday, in the call, I asked about embeds and if I remember correctly, @petrspelos  said they weren't implemented yet. Wouldn't we need to create that first? Or will I just create a non-embedded userinfo command?

**Comment by petrspelos** [comment]
With @DraxCodes we agreed that the ideal implementation of an embed would be a SendMessage overload. That would mean expanding [this interface](https://github.com/discord-bot-tutorial/Miunie/blob/master/src/Miunie.Core/Discord/IDiscordMessages.cs#L7) to contain a `SendMessage` method that takes in the whole User object with all the information we'd like to display.

The implementor of this interface, which is [this class](https://github.com/discord-bot-tutorial/Miunie/blob/master/src/Miunie.Discord/DSharpPlusDiscord.cs) can then take that object and send it in form of an embed. Basically it knows how to send that type of an object as an embed.

Hope that makes sense. :blush:

**Comment by svr333** [comment]
It does make sense. I think I get what you mean. One more question - do we make a different SendMessage method for each type of input (as in, userinfo will have different params than for instance a serverinfo command), or do we just generalize it so they all fit in one?

Hopefully you understand what I mean.

**Comment by petrspelos** [comment]
I think those should be separate. It will be easier to edit individual embeds that way and there most likely won't be that many of those. :slightly_smiling_face:

**Comment by svr333** [comment]
Gotcha. I'll get on it whenever I can afford to.

**Comment by petrspelos** [comment]
I'm on it. :sweat_smile:
