### ISSUE TITLE
Implement Guild Info

### ISSUE THREAD

**Issue by DraxCodes** [discord-bot-tutorial/Miunie#74]
This would be an extension of the user profile info. Essentially it would output a fancy embed or something like that of the guild the command was used in.

```diff
+ Guild ID
+ Roles,
+ Admins (Based on the administrator permision)
+ Created @
+ Job's a good en.
```

Any further ideas for the implementation of the command, please post below.

**Comment by petrspelos** [comment]
Thanks, @DraxCodes! Great suggestion. :1st_place_medal: 

In terms of implementation, I'm thinking this would require:
* Creation of `MiunieGuild` class with all this information.
* Creation of a Convertor that would be able to create it out of `DiscordGuild`.

For the embeds, I think we could use the strategy we discussed earlier:
In `Miunie.Core`, we would extend the `IDiscordMessages` interface with a
```cs
void SendMessage(MiunieChannel targetChannel, MiunieGuild payload);
```
The `DSharpPlusDiscord` class that implements this interface inside `Miunie.Discord` would then create the embed out of the `MiunieGuild payload` and send it.
