### ISSUE TITLE
LanguageResources bug when using Visual Studio IDE

### ISSUE THREAD

**Issue by petrspelos** [discord-bot-tutorial/Miunie#75]
With @DraxCodes and @svr333, we discovered that Miunie will not work properly when run from the Visual Studio IDE. (Either in debug or without debugging).

While Miunie will start up, she will not respond to any command that uses `LanguageResources`.

> :information_source: The workaround for this issue is to run `Miunie.ConsoleApp` with the `dotnet run` command from a command line.

*****

## How can you help? :thinking: 

* Confirming that you can reproduce this problem on a Visual Studio IDE installation. _(Feel free to comment bellow)_
* Suggesting possible solutions / Pull Requesting a fix
* Adding a mention about this issue in the `README.md` file.

**Comment by svr333** [comment]
I'll add it to the README.md file for now.

**Comment by SirDragonKnight** [comment]
I can confirm that this is in an issue in
1.Visual Studio Community 2-17
2. Windows 10

Seems like the help and profile command work (gives output in discord) but I see no messages in the command prompt of any kind for any of the commands.

**Comment by petrspelos** [comment]
Resolved with fa79052a74beff1002196f0b29861e95e8819250
