### ISSUE TITLE
Create Command Documentation

### ISSUE THREAD

**Issue by petrspelos** [discord-bot-tutorial/Miunie#78]
We need to start documenting our commands. Currently you can see the commands with
```
@Miunie help
```

But we should have a new `Commands.md` file in our `docs/` directory.

I suggest using a Markdown table to organize the commands. Let's also include a little description of each command and I think it would be **super cool** :1st_place_medal: if we could add a little gif of using that command into like an Example column.

On Windows I recommend "ScreenToGif", it's an open source program that allows you to record a part of your screen and save it as a .gif. (for GitHub design purposes, I recommend using a Light theme for Discord)

**Comment by svr333** [comment]
I'll be willing to create the design and add the first few commands to the documentation. I'll even hurt myself by switching Discord to light theme for a bit. I'll do it later today or tomorrow, it'll depend on how fast I can finish my schoolwork.

**Comment by svr333** [comment]
Issue fixed with #82
