### ISSUE TITLE
Implementation of different languages

### ISSUE THREAD

**Issue by svr333** [discord-bot-tutorial/Miunie#80]
### Adding a Dutch language file IF possible

Is it possible to have more languages than just English setup at the moment? As in, would anyone be able to let's say add a phrasesFr.Json file?

If so, would it be okay if I created the phrasesNl.json (Dutch) file?

And if that isn't an option yet, we might want to make it an option since it can be useful for people who do not speak proper English or might understand more in their language.

### Implementation idea:
Maybe we could even make it so each user decides which language they want their replies in, if the server which they execute in allow different languages than the server's default.
What I mean with this is that, for example, we are in `Guild x` and we have `User y.`

**Case 1:**
The Guild's default language is English and the Guild also allows users to have a different language than the Guild's default. *User y* has Russian as his standard language.

When *User y* receives a message from the bot, probably after executing a command, it'll be shown in Russian since the server allows 'custom' languages and *y's* language is Russian.

***Case 2:***
The Guild's default language is English and the Guild **DOESN'T** allow users to have a different language than the Guild's default. *User y* has Russian as his standard language.

Now when *User y* receives a message from the bot, it'll be shown in English since the server doesn't allow 'custom' languages.

### Feedback

This idea could be considered 'too much' and I would agree with it, although I think it's a cool add-on we could add in the (far) future maybe.

I'm open for any thoughts/suggestions/changes on this idea.

**Comment by Charly6596** [comment]
+1 to support more languages, it was already a feature, sadly removed with #71

**Comment by petrspelos** [comment]
It was _supported_, however it was far from a feature.
The implementation that was present was hardcoded into English and never used.

So the bottom line is... It's better to keep a simpler version of what we're actually using.

I agree this should be an issue. Good call on that, @svr333. But it should get resolved once it's ACTUALLY implemented.

**Comment by Charly6596** [comment]
I don't know what's the current state of this issue, did you discuss about this in the discord server? 
I've been dealing with a web framework for the last few months, and it has an interesting translation system, I'll try to explain how it works, maybe we can take some ideas from that;
So, I'll talk from the _plugin developer_ point of view, whenever I want a string to be translatable, I use a method from the language service which takes two arguments, the said string, and another string, being a _translation group_. This would make that string translatable, the group is mainly to organize the strings. In the backoffice (admin dashboard) the admin, or anyone else with permissions, would have an option to modify the translations, which are grouped by plugin/translation group(s)/string. For example, let's say I have a string, "Your message here", which i want to translate, so, in my code, i'd use the method mentioned above, indicating the translation group:
```cs
_lang.Translate("Your message here", "Forms.Help");
```
I'm indicating I have a string which is in a subgroup, Help, which is in a group, Forms. This is how it would look like:
![image](https://user-images.githubusercontent.com/13708100/55840095-82a33980-5b2a-11e9-8d85-5002c688f974.png)
In the picture also indicates there's a Shop group. It's a kind of master group. 
Regardless of the language i translate to, i will always see the same string "Your messge here", and the subgroups there.
The main advantage of this translation system i see is the developers doesn't have to care about specifying a translation key in an enum, or to write the translation in a json file manually, the translation system do it for you. You can of course have json files with the translated strings, as storage, but won't have to worry about that while making a string translatable.

In Miunie we could have something similar, for example, imo, would be super cool to be able to do this in from the `ProfileService`
```cs
_lang.Translate("Oops, seems like {0} doesn't have any reputation interaction yet", "Profile.Reputation", user.Name);
```
What do you guys think about that? Do you see any downsides in that system? Did you have in mind something else?

**Comment by petrspelos** [comment]
If translation is implemented, it will be done through a LanguageResourceFactory. No need to pollute the API with more arguments.
```
var langResources = _langResourceFactory.Create(Language.English);
```

**Comment by petrspelos** [comment]
Don't start on this one now, however, the multiple front ends and .NET Core 3 comes first.
