### ISSUE TITLE
Convert LanguageResources to a Provider

### ISSUE THREAD

**Issue by petrspelos** [discord-bot-tutorial/Miunie#86]
The **LanguageResources** class is really a provider and should be refactored to reflect that.
It should be refactored into `Miunie.Core/Providers/LanguageProvider.cs` (with an appropriate interface).

**Comment by SirDragonKnight** [comment]
I've completed this in the fork I have. Hopefully you can merge, not sure what i can do on my end cause of my git issues.

**Comment by Charly6596** [comment]
@SirDragonKnight You have to create a Pull Request, to request to merge, right here
![image](https://user-images.githubusercontent.com/13708100/55378817-e621db80-551a-11e9-8506-c7678bcf9657.png)
It's at the right side, in your repository.
Once you click there, you have to pick your repo at the right side, so the arrow should point from your repository to this one
![image](https://user-images.githubusercontent.com/13708100/55379013-af989080-551b-11e9-9e42-29520613f20e.png)
Click create pull request and then fill up the pull request template and open it
if you find any issues try to follow this article https://help.github.com/en/articles/creating-a-pull-request

**Comment by petrspelos** [comment]
Thanks, @Charly6596.

**Comment by SirDragonKnight** [comment]
Thanks @Charly6596

**Comment by petrspelos** [comment]
Still not finished, should also delete the old Resources and update the tests.
